# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: iCodingProgram
brief-intro: iOSer
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://icodingprogram.com" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
twitter_username: 9_drops
facebook_username:
github_username:  9drops
email: zhanbz@hotmail.com
weibo_username:
zhihu_username: 
linkedIn_username: 
dribbble_username:

description_footer: 编程、学习、思考

#gitment
comment_gitment_repo: 9drops.github.io
comment_gitment_clientId: 1969e28cce378f26d04a
comment_gitment_clientSecret: 0e52cda1cea8a74d84bbd70f9a31136b8a1568ea

# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
baidu_tongji_id: 8bbd3606509f52f3a6c837e4e15d9747
google_analytics_id: # google 分析追踪id

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-paginate]
paginate: 6
